### ISSUE TITLE
Request for an explicit LICENSE

### ISSUE THREAD

**Issue by jevinskie** [CenturionInfoSec/konyutils#3]
Hi,

Thanks for these Frida tools/agents! I’d like to update them but lacking a LICENSE I don’t know how to attribute your work properly or how to license my derivative.

Could you please add a license, preferably BSD 2 clause/MIT/zlib or something similar?

Thanks,
Jevin

**Comment by ryanbaxendale** [comment]
I added the MIT licence. Please let us know where you plan to use this and credit us and the original author - https://github.com/ayrx

**Comment by jevinskie** [comment]
Thank you, will do!
